"""
report_generator.py

Generates HTML reports for the ML pipeline stages.
Uses the actual outputs generated by the current pipeline.
"""

from pathlib import Path
from datetime import datetime
import pandas as pd


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

REPORTS_DIR = PROJECT_ROOT / "reports"
RESULTS_DIR = PROJECT_ROOT / "results" / "metrics"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
SPLITS_DIR = PROJECT_ROOT / "data" / "splits"
SUBMISSION_DIR = PROJECT_ROOT / "results" / "submissions"

REPORTS_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# GENERIC HTML REPORT GENERATOR
# ============================================================

def generate_html_report(title: str, sections: dict, output_name: str):

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">

        <title>{title}</title>

        <style>

            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                background-color: #f9f9f9;
                color: #333;
            }}

            h1 {{
                color: #1f4e79;
            }}

            h2 {{
                color: #2e75b6;
                border-bottom: 2px solid #ddd;
                padding-bottom: 5px;
                margin-top: 30px;
            }}

            table {{
                border-collapse: collapse;
                width: 100%;
                margin: 15px 0;
                background: #fff;
            }}

            th, td {{
                border: 1px solid #ddd;
                padding: 10px;
                text-align: left;
            }}

            th {{
                background-color: #f2f2f2;
            }}

            .container {{
                background: #fff;
                padding: 30px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0,0,0,0.05);
            }}

            .footer {{
                margin-top: 40px;
                font-size: 12px;
                color: #666;
                text-align: center;
            }}

            .highlight-box {{
                background-color: #f0f4f8;
                border-left: 4px solid #1f4e79;
                padding: 15px;
                margin: 15px 0;
            }}

        </style>

    </head>

    <body>

    <div class="container">

        <h1>{title}</h1>

        <p>
            <strong>Generated:</strong>
            {datetime.now().strftime('%Y-%m-%d %H:%M')}
        </p>
    """

    for section_title, content in sections.items():

        html += f"""
        <h2>{section_title}</h2>
        {content}
        """

    html += """
        <div class="footer">
            AI-Assisted ML Project Platform | Governance & Reporting Layer
        </div>

    </div>

    </body>
    </html>
    """

    html_path = REPORTS_DIR / f"{output_name}.html"

    html_path.write_text(
        html,
        encoding="utf-8"
    )

    print(f"Report successfully saved -> {html_path}")

    return html_path


# ============================================================
# 1. PROBLEM FORMULATION REPORT
# ============================================================

def generate_problem_formulation_report():

    sections = {

        "1. Problem Statement": """
            <p>
                Real-estate stakeholders, buyers, and investors require
                accurate, data-backed property valuations to support
                real-estate decisions.
            </p>
        """,

        "2. Business Problem to Data Analytical Problem": """

            <div class="highlight-box">

                <p>
                    <strong>Business Problem:</strong>
                    How can property values be estimated accurately
                    using available housing attributes?
                </p>

                <p>
                    <strong>Data Analytical Problem:</strong>
                    Can historical housing attributes be used to
                    reliably predict continuous property valuations?
                </p>

            </div>
        """,

        "3. Data Problem": """

            <p>
                The housing dataset requires preprocessing before
                machine-learning modeling.
            </p>

            <ul>

                <li>
                    <strong>Missing Values:</strong>
                    Missing attribute values require imputation.
                </li>

                <li>
                    <strong>Feature Transformation:</strong>
                    Categorical variables require numerical encoding.
                </li>

                <li>
                    <strong>Feature Engineering:</strong>
                    Household-level ratio features are generated.
                </li>

                <li>
                    <strong>Feature Scaling:</strong>
                    Numerical variables are transformed as required
                    during preprocessing.
                </li>

            </ul>
        """,

        "4. Problem Type Framing": """

            <p>
                The target variable is
                <code>median_house_value</code>.
            </p>

            <div class="highlight-box">

                <p>
                    <strong>Problem Type:</strong>
                    Supervised Regression
                </p>

                <p>
                    <strong>Evaluation Metrics:</strong>
                    RMSE, MAE and R²
                </p>

            </div>
        """
    }

    return generate_html_report(
        "Problem Formulation & Framing Report",
        sections,
        "01_problem_formulation_report"
    )


# ============================================================
# 2. EDA REPORT
# ============================================================

def generate_eda_report():

    candidate_path = (
        PROJECT_ROOT
        / "results"
        / "eda_analysis_summary"
        / "candidate_explanatory_variables.csv"
    )

    if candidate_path.exists():

        df = pd.read_csv(candidate_path)

        table_html = df.to_html(
            classes="table",
            index=False
        )

        sections = {

            "Overview": """
                <p>
                    This report summarizes the candidate explanatory
                    variables identified during exploratory data analysis.
                </p>
            """,

            "Candidate Explanatory Variables":
                table_html
        }

        return generate_html_report(
            "EDA Analytical Summary",
            sections,
            "02_eda_report"
        )

    print(
        f"EDA candidate-variable file not found at: {candidate_path}"
    )

    return None


# ============================================================
# 3. PREPROCESSING REPORT
# ============================================================

def generate_preprocessing_report():

    train_path = SPLITS_DIR / "train.csv"
    validation_path = SPLITS_DIR / "validation.csv"
    test_path = SPLITS_DIR / "test.csv"

    train_rows = "Not available"
    validation_rows = "Not available"
    test_rows = "Not available"

    if train_path.exists():
        train_rows = len(pd.read_csv(train_path))

    if validation_path.exists():
        validation_rows = len(pd.read_csv(validation_path))

    if test_path.exists():
        test_rows = len(pd.read_csv(test_path))

    feature_names_path = (
        PROCESSED_DIR / "feature_names.csv"
    )

    feature_count = "Not available"

    if feature_names_path.exists():

        feature_df = pd.read_csv(
            feature_names_path
        )

        feature_count = len(feature_df)

    sections = {

        "Preprocessing Overview": """
            <p>
                The dataset was split into training, validation,
                and test datasets before preprocessing.
                Feature engineering and preprocessing were then
                applied consistently across the datasets.
            </p>
        """,

        "Dataset Statistics": f"""

            <ul>

                <li>
                    <strong>Training Rows:</strong>
                    {train_rows}
                </li>

                <li>
                    <strong>Validation Rows:</strong>
                    {validation_rows}
                </li>

                <li>
                    <strong>Test Rows:</strong>
                    {test_rows}
                </li>

                <li>
                    <strong>Split Ratio:</strong>
                    70% / 15% / 15%
                </li>

                <li>
                    <strong>Model Features:</strong>
                    {feature_count}
                </li>

            </ul>
        """,

        "Feature Engineering": """

            <p>
                The preprocessing stage creates the following
                household-level engineered features:
            </p>

            <ul>

                <li>rooms_per_household</li>

                <li>population_per_household</li>

                <li>bedrooms_per_household</li>

            </ul>
        """,

        "Preprocessing Operations": """

            <ul>

                <li>
                    Numerical conversion
                </li>

                <li>
                    Missing-value handling
                </li>

                <li>
                    Infinite-value handling
                </li>

                <li>
                    Categorical encoding
                </li>

                <li>
                    Consistent feature alignment
                    across train, validation and test data
                </li>

            </ul>
        """
    }

    return generate_html_report(
        "Preprocessing & Feature Engineering Report",
        sections,
        "03_preprocessing_report"
    )


# ============================================================
# 4. TRAINING REPORT
# ============================================================

def generate_training_report():

    comparison_path = (
        RESULTS_DIR
        / "validation_model_comparison.csv"
    )

    if not comparison_path.exists():

        print(
            f"Training comparison file not found at: "
            f"{comparison_path}"
        )

        return None

    comparison_df = pd.read_csv(
        comparison_path
    )

    table_html = comparison_df.to_html(
        classes="table",
        index=False
    )

    # Try to determine the best model dynamically
    best_model_name = "Not available"
    best_rmse = "Not available"

    rmse_columns = [
        col for col in comparison_df.columns
        if "rmse" in col.lower()
    ]

    model_columns = [
        col for col in comparison_df.columns
        if col.lower() in ["model", "model_name", "algorithm"]
    ]

    if rmse_columns:

        rmse_col = rmse_columns[0]

        best_index = comparison_df[rmse_col].idxmin()

        best_rmse = comparison_df.loc[
            best_index,
            rmse_col
        ]

        if model_columns:

            best_model_name = comparison_df.loc[
                best_index,
                model_columns[0]
            ]

    sections = {

        "Model Training Overview": """
            <p>
                Multiple supervised regression models were trained
                and compared using the validation dataset.
            </p>

            <p>
                The current pipeline compares:
            </p>

            <ul>

                <li>Ridge Regression</li>

                <li>Random Forest Regressor</li>

                <li>Gradient Boosting Regressor</li>

            </ul>
        """,

        "Validation Model Comparison":
            table_html,

        "Winning Model Selection": f"""

            <div class="highlight-box">

                <p>
                    <strong>Best Model:</strong>
                    {best_model_name}
                </p>

                <p>
                    <strong>Best Validation RMSE:</strong>
                    {best_rmse}
                </p>

            </div>

        """
    }

    return generate_html_report(
        "Model Training & Validation Report",
        sections,
        "04_model_validation_report"
    )


# ============================================================
# 5. SUBMISSION / EVALUATION REPORT
# ============================================================

def generate_submission_report():

    metrics_path = (
        RESULTS_DIR
        / "test_evaluation_metrics.csv"
    )

    submission_path = (
        SUBMISSION_DIR
        / "submission.csv"
    )

    sections = {

        "Pipeline Completion": """
            <p>
                The machine-learning pipeline completed the
                training and evaluation stages successfully.
            </p>
        """,

        "Test Set Evaluation": """
            <p>
                The frozen best model was evaluated on the
                held-out test dataset.
            </p>
        """
    }

    if metrics_path.exists():

        metrics_df = pd.read_csv(
            metrics_path
        )

        sections["Test Evaluation Metrics"] = (
            metrics_df.to_html(
                classes="table",
                index=False
            )
        )

    if submission_path.exists():

        sections["Submission Export"] = f"""

            <p>
                Test predictions were exported successfully.
            </p>

            <p>
                <strong>File:</strong>
                {submission_path}
            </p>

        """

    else:

        sections["Submission Export"] = """

            <p>
                Submission file has not yet been generated.
            </p>

        """

    return generate_html_report(
        "Final Submission & Evaluation Report",
        sections,
        "05_final_submission_report"
    )


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("GENERATING ML PIPELINE REPORTS")
    print("=" * 60)

    # 1. Problem formulation
    generate_problem_formulation_report()

    # 2. EDA
    generate_eda_report()

    # 3. Preprocessing
    generate_preprocessing_report()

    # 4. Training
    generate_training_report()

    # 5. Evaluation / submission
    generate_submission_report()

    print("\n" + "=" * 60)
    print("REPORT GENERATION COMPLETED")
    print("=" * 60)

    print(f"\nReports generated in:")
    print(REPORTS_DIR)