from pathlib import Path
import pandas as pd
from sklearn.model_selection import train_test_split

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Read directly from raw data generated by ingest.py
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "housing.csv"

SPLIT_DATA_DIR = PROJECT_ROOT / "data" / "splits"

TRAIN_DATA_PATH = SPLIT_DATA_DIR / "train.csv"
VALIDATION_DATA_PATH = SPLIT_DATA_DIR / "validation.csv"
TEST_DATA_PATH = SPLIT_DATA_DIR / "test.csv"

RANDOM_STATE = 42


def load_raw_data(file_path: Path = RAW_DATA_PATH) -> pd.DataFrame:
    """Load the raw housing dataset downloaded from ingest.py."""
    if not file_path.exists():
        raise FileNotFoundError(
            f"Raw data file not found: {file_path}. "
            "Please execute `ingest.py` first."
        )
    return pd.read_csv(file_path)


def add_income_category(df: pd.DataFrame) -> pd.DataFrame:
    """Create a temporary income category for stratified splitting."""
    stratified_df = df.copy()

    stratified_df["income_category"] = pd.cut(
        stratified_df["median_income"],
        bins=[0, 1.5, 3.0, 4.5, 6.0, float("inf")],
        labels=[1, 2, 3, 4, 5],
        include_lowest=True,
    )

    if stratified_df["income_category"].isna().any():
        raise ValueError(
            "Some observations could not be assigned to an income category."
        )

    return stratified_df


def split_data(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Split data into 70% training, 15% validation, and 15% test sets."""
    stratified_df = add_income_category(df)

    train_df, temporary_df = train_test_split(
        stratified_df,
        test_size=0.30,
        random_state=RANDOM_STATE,
        stratify=stratified_df["income_category"],
    )

    validation_df, test_df = train_test_split(
        temporary_df,
        test_size=0.50,
        random_state=RANDOM_STATE,
        stratify=temporary_df["income_category"],
    )

    train_df = train_df.drop(columns="income_category").reset_index(drop=True)
    validation_df = validation_df.drop(columns="income_category").reset_index(drop=True)
    test_df = test_df.drop(columns="income_category").reset_index(drop=True)

    return train_df, validation_df, test_df


def validate_splits(
    original_df: pd.DataFrame,
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> None:
    """Validate the sizes and separation of the three datasets."""
    total_split_rows = len(train_df) + len(validation_df) + len(test_df)

    if total_split_rows != len(original_df):
        raise ValueError(
            "The total number of rows in the splits does not match the original dataset."
        )

    expected_columns = set(original_df.columns)
    for split_name, split_df in {
        "training": train_df,
        "validation": validation_df,
        "test": test_df,
    }.items():
        if set(split_df.columns) != expected_columns:
            raise ValueError(f"The {split_name} set has incorrect columns.")

    print("Split validation passed.")


def save_splits(
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> None:
    """Save the train, validation, and test datasets."""
    SPLIT_DATA_DIR.mkdir(parents=True, exist_ok=True)

    train_df.to_csv(TRAIN_DATA_PATH, index=False, encoding="utf-8")
    validation_df.to_csv(VALIDATION_DATA_PATH, index=False, encoding="utf-8")
    test_df.to_csv(TEST_DATA_PATH, index=False, encoding="utf-8")

    print(f"Training data saved to:   {TRAIN_DATA_PATH}")
    print(f"Validation data saved to: {VALIDATION_DATA_PATH}")
    print(f"Test data saved to:       {TEST_DATA_PATH}")


def print_split_summary(
    original_df: pd.DataFrame,
    train_df: pd.DataFrame,
    validation_df: pd.DataFrame,
    test_df: pd.DataFrame,
) -> None:
    """Display the size and percentage of each split."""
    total_rows = len(original_df)

    print("=" * 40)
    print("DATA SPLIT SUMMARY")
    print("=" * 40)
    print(f"Original dataset: {total_rows} rows")
    print(f"Training set:     {len(train_df)} rows ({len(train_df) / total_rows:.1%})")
    print(f"Validation set:   {len(validation_df)} rows ({len(validation_df) / total_rows:.1%})")
    print(f"Test set:         {len(test_df)} rows ({len(test_df) / total_rows:.1%})")
    print("=" * 40)


if __name__ == "__main__":
    housing_df = load_raw_data()
    train_data, validation_data, test_data = split_data(housing_df)
    validate_splits(housing_df, train_data, validation_data, test_data)
    save_splits(train_data, validation_data, test_data)
    print_split_summary(housing_df, train_data, validation_data, test_data)